import CustomContainer from "@/component/container";
import { Header } from "@/component/Header";
import { MenuSidebar } from "@/component/MenuSidebar";
import { Providers } from "@/provider";
import { Flex } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({ subsets: [], weight: ["300", "400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <Providers>
          <CustomContainer>
            <Flex
              flexDir="column"
              minW="100vw"
              minH="100vh"
              bgColor="neutral.gray.2"
            >
              <Header title="FUTEBOL EM TEMPO REAL" />
              <Flex flex={1}>
                <MenuSidebar />
                {children}
              </Flex>
            </Flex>
          </CustomContainer>
        </Providers>
      </body>
    </html>
  );
}
